import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import styled from 'styled-components';
import { useState } from 'react'; 
import axios from 'axios';
import Header from '@/components/header/header';
import Card from '@/components/card/card';
import { Player, Controls } from '@lottiefiles/react-lottie-player';
import Logo from '@/public/Logo2.png'

const Background = styled.div`
width:100vw;
max-height:100vh;
height:100%;
background: linear-gradient(to bottom right, #FFFFFF 0%, #3cc0fe 60%, #0066ff);
position:absolute;
z-index:-1;
`

const LogoCont = styled.div`
position:absolute;
top: 5%;
left: 8%;
display:flex;
`

const Input = styled.input`
margin-top:5%;
border-radius:5px;
font-family: 'Unbounded';
color:#802392;
width:80%;
`


export default function Home() {

  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');



  var apiKey =process.env.NEXT_PUBLIC_apiKey;
  var lang = "kr";
  var units = "metric";

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`;
  console.log(url)

  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)
      .then((response)=> {
        console.clear()
        setData(response.data);
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("");

      }).catch(err => {
        console.log(err);
        setErrorMessage("Please enter another location");
        setData({});
        setWeather();
      })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>TracSKY</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@500&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet"></link>
      </Head>

      <LogoCont className={styles.logocont}>
        <Image style={{position:'absolute'}}src={Logo} width={135} height={40} alt="logo"/>
      </LogoCont>
      
      <Background/>

      <main className={styles.main}>

          <div className={styles.col3}>
            <Input className={styles.effect4}
            type="text"
            value = {location}
            onChange= {event => setLocation(event.target.value)}
            placeholder = "Enter Location"
            onKeyDown= {searchLocation}/>

            <span className={styles.focusborder}/>
          </div>


        {
          weather && weather.map((w, index) => {
            return (
              <div key={index}>
                <Card
                temp={data.main.temp}
                city={data.name}
                desc={w.description}
                main={w.main}
                feels={data.main.feels_like}
                gust={data.wind.gust}
                icon={`${w.main}.json`}
                />
              </div>
            )
          })
        }

      </main>
    </>
  )
}
